export const checkLabels: Record<string, string> = {
  assignment: "用途关联",
  project_configuration: "项目配置",
  project_input: "项目需求",
  product_constraint: "客户选型要求",
  budget: "客户预算",
  inspection: "用途检查依据",
  role_allocation: "角色数量分配",
  selection: "角色选型",
  compatibility: "产品适配",
  sharing: "共用部署",
  capacity: "资源容量",
  resource_policy: "容量检查口径",
  included_allocation: "已含内容抵扣",
  accessory_allocation: "配套分配",
  coverage: "系统知识范围",
  supply: "供货核算",
  accessory_choice: "选配状态",
};
